"""create complaints table

Revision ID: 090a4539a3a1
Revises: 
Create Date: 2026-09-26 00:28:09.264509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '090a4539a3a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('reporter_contact', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('water', 'electricity', 'sanitation', 'roads', 'streetlights', 'other', name='category'), nullable=False),
    sa.Column('priority', sa.Enum('high', 'normal', 'low', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'rejected', name='status'), nullable=False),
    sa.Column('ai_summary', sa.String(length=140), nullable=True),
    sa.Column('triaged_by', sa.String(length=50), nullable=False),
    sa.Column('triage_latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(location) >= 3 AND length(location) <= 200', name='location_length_check'),
    sa.CheckConstraint('length(text) >= 10 AND length(text) <= 2000', name='text_length_check'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaints')
    # ### end Alembic commands ###
