"""add status priority and created_at indexes

Revision ID: e099d960dc4c
Revises: 090a4539a3a1
Create Date: 2026-09-26 00:33:46.664222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e099d960dc4c'
down_revision: Union[str, None] = '090a4539a3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_complaints_created_at', 'complaints', ['created_at'], unique=False)
    op.create_index('ix_complaints_status_priority', 'complaints', ['status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_complaints_status_priority', table_name='complaints')
    op.drop_index('ix_complaints_created_at', table_name='complaints')
    # ### end Alembic commands ###
